version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: hmt_postgres
    restart: always
    environment:
      POSTGRES_DB: hmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hmt_network

  redis:
    image: redis:7
    container_name: hmt_redis
    restart: always
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - hmt_network

  app:
    build: .
    container_name: hmt_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD:  ${SPRING_DATASOURCE_PASSWORD}
      OTP_REDIS_URI: ${OTP_REDIS_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      JWT_REFRESH_EXPIRATION_SECONDS: ${JWT_REFRESH_EXPIRATION_SECONDS}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_STARTTLS}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: ${SPRING_MAIL_STARTTLS}
      SUPERADMIN_EMAIL: ${SUPERADMIN_EMAIL}
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - hmt_network

volumes:
  pgdata:

networks:
  hmt_network: